# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Lee McAlilly
email: lee@originalfuzz.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal website and journal for Lee McAlilly, founder of Original Fuzz and web developer. Soccer enthusiast. Raised in Mississippi now residing in Nashville, TN.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://leemcalilly.github.io" # the base hostname & protocol for your site, e.g. http://example.com

facebook_username: originalfuzz
github_username: leemcalilly
instagram_username: originalfuzz
spotify_url: https://open.spotify.com/user/djoriginalfuzz?si=2hZZSFliRuemICnXMDKiRA
stackoverflow_url: https://stackoverflow.com/users/168286/lee-mcalilly?tab=profile
twitter_username: original_fuzz
youtube_username: OriginalFuzz

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "note"


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
